apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipt-service
  namespace: shop-giay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipt-service
  template:
    metadata:
      labels:
        app: recipt-service
    spec:
      containers:
        - name: recipt-service
          image: huyboy204/recipt_service_be:2.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: recipt-service
  namespace: shop-giay
spec:
  type: LoadBalancer
  ports:
    - port: 3003
      targetPort: 3000
  selector:
    app: recipt-service
