apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shop-giay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: huyboy204/product_service_be:2.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shop-giay
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3000
  selector:
    app: product-service
